version: "3.3"

services:
  nginx:
    restart: always
    build: .
    volumes:
      - /var/www/ThalosCinemaSystem/staticfiles:/var/www/ThalosCinemaSystem/staticfiles
      - /var/www/ThalosCinemaSystem/staticfiles:/var/www/ThalosCinemaSystem/mediafiles
    ports:
      - "80:80"
    networks:
      - nginx_network

networks:
  nginx_network:
    external: true