apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  rules:
  - host: cms-infoboard.wronamichal.pl
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: varnish
              port:
                number: 80
#  - http:
#      paths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#            name: varnish
#            port:
#              number: 80

  - host: djqubus.wronamichal.pl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: varnish
            port:
              number: 80

  - host: infoboard.wronamichal.pl
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: varnish
              port:
                number: 80