---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-app
spec:
  selector:
    matchLabels:
      app: order-app
  replicas: 1
  template:
    metadata:
      labels:
        app: order-app
    spec:
      containers:
      - name: order-app
        image: ghcr.io/michalwrona01/order-song-app:sha256-a2ae4adcbaa2bf1a4e71440d5dde8a29b962d32eff0e30fd83f962055ec8235f.sig
        command:
          - daphne -b 0.0.0.0 -p 8080 main:app
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: order-app
  labels:
    app: order-app
spec:
  type: ClusterIP
  selector:
    app: order-app
  ports:
  - name: http
    port: 80
    targetPort: 8080
